version: "3.9"

services:
  postgres:
    container_name: postgres14_hse_lab_2
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hse_lab_2
    volumes:
      - type: bind
        source: ./results
        target: /results
      - type: bind
        source: ./scripts
        target: /scripts